plugins:
  league_enabled:
    default: true
    client: true
  league_license_key:
    default: ""
    client: false
  league_licensed_bronze:
    default: false
    client: true
    hidden: true
  league_licensed_silver:
    default: false
    client: true
    hidden: true
  league_licensed_gold:
    default: false
    client: true
    hidden: true

discourse_league:
  league_go_live:
    default: false
    client: true
  league_contact_user:
    default: ''
    type: username
  league_currency:
    client: true
    type: enum
    default: "USD"
    choices:
      - "CAD"
      - "EUR"
      - "GBP"
      - "USD"
  league_gateway:
    client: true
    type: enum
    default: "Braintree"
    choices:
      - "Braintree"
  league_include_paypal:
    default: false
    client: true
  league_paypal_username:
    default: ""
    client: false
  league_paypal_password:
    default: ""
    client: false
  league_paypal_signature:
    default: ""
    client: false
  league_braintree_merchant_id:
    default: ""
    client: false
  league_braintree_public_key:
    default: ""
    client: false
  league_braintree_private_key:
    default: ""
    client: false